id: Vendr
name: Vendr
type: Product
description: 
supportedBy: core

packageVersion: 1.5.1
docVersions:
  next: 1.6.0
  current: 1.5.0
  previous: 
  - 1.4.0
  - 1.3.0
  - 1.2.0
  - 1.0.0

links:
  - title: Versions
    link: /versions/
  - title: Changelog
    link: /changelog/
